apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1-deployment
  labels:
    app: webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80