apiVersion: v1
kind: Pod
metadata:
  name: container1
  labels:
    app: container1
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always